### ISSUE TITLE
Densha de GO controller not supported

### ISSUE THREAD

**Issue by Nekokabu** [raphnet/pj64raphnetraw#1]
![image](https://cloud.githubusercontent.com/assets/11252775/22505493/20cf6a60-e8bf-11e6-92bf-21d48da42927.png)

To use Densha de GO controller, need to connect it to port 3, normal controller to port 1.
In addition, need to connect it to port 4 to use VRU.

**Comment by raphnet** [comment]
So to play this game with all the features, you need this:

- N64 controller in port 1
- Densha de GO! controller in port 3
- VRU in port 4

Correct?

Here are a few ways that should work:
- If you have two adapters (eg: 1 single port + 1 dual port), connect both and use the "ports 1 and 4" special plugin.
- If you have two dual-port adapters, connect both and use the standard plugin.
- If you only have one dual-port adapter, and wish to use the Densha de GO! controller + a standard controller, you can use the "ports 1 and 3" special plugin included in this new release:

[pj64raphnetraw-1.0.1.zip](https://github.com/raphnet/pj64raphnetraw/files/752282/pj64raphnetraw-1.0.1.zip)

**Comment by Nekokabu** [comment]
>So to play this game with all the features, you need this:
>
>N64 controller in port 1
>Densha de GO! controller in port 3
>VRU in port 4
>Correct?

yes.

I got N64 / GC adapter and dual N64 adapter now.
I confirmed Densha de GO! Controller support.

pj64raphnetraw_ports1and3.dll is something wrong.
It looks like a standard plugin.
![image](https://cloud.githubusercontent.com/assets/11252775/22885193/a991e910-f23b-11e6-9ba6-9e644fe34e2e.png)

**Comment by DerekTurtleRoe** [comment]
@Nekokabu @raphnet So can this be closed since it works now?
